### ISSUE TITLE
[Bug]: No gui change after you click continue button after claiming reward

### ISSUE THREAD

**Issue by 2vb** [ThatGravyBoat/RewardClaim#2]
### Bug Description

The gui did not close after I clicked the continue button to claim my reward and did not know the reward was claimed.

### Expected Behavior

I expected the GUI to close

### Version

1.01

### Mod Loader Version

1.8.9-forge1.8.9-11.15.1.2318-1.8.9

### Logs or additional context

https://pastebin.com/L5UUhHZ9

**Comment by ThatGravyBoat** [comment]
Ive put out a version that should show an error if an error happens during claiming if you can reproduce this error with this new version please comment on this issue. https://github.com/ThatGravyBoat/RewardClaim/releases/tag/v1.0.2

**Comment by 2vb** [comment]
sometimes the gui doesnt even show up to claim my rewards
