### ISSUE TITLE
[BUG]: The Mod Don't Load

### ISSUE THREAD

**Issue by DEMnetwork** [ThatGravyBoat/RewardClaim#6]
### Bug Description

LOG:

16:56:48.940
launcher
main
Using default game log configuration client-1.12.xml (outputs XML)
16:56:49.868
Quilt Loader/GameProvider
main
Loading Minecraft 1.19.4 with Quilt Loader 0.19.2

[...]

16:56:52.423
Quilt Loader/Discovery
main
Unknown file in mods folder: <mods>/RewardClaim-1.0.5.jar

### How to Reproduce?

Doewnload The Mod
Install The Mod
Launch The Game Then,
Read Logs
And You'll See The Error

### Expected Behavior

Mod Load

### Version

1.0.5

### Mod Loader Version

Quilt Loader 0.19.2-1.19.4

**Comment by DEMnetwork** [comment]
How Do I Solve That Problem?

**Comment by NopoTheGamer** [comment]
reward claim is for 1.8.9 only

**Comment by ThatGravyBoat** [comment]
Yeah 1.8.9 only
